version: '2'

services:
 
  elasticsearch:
    build:
      context: ./elasticsearch
    container_name: "elasticsearch-monitoring"
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./db/es-data:/usr/share/elasticsearch/data

  kibana:
    build:
      context: ./kibana
    container_name: "kibana-monitoring"
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch