# https://github.com/elastic/elasticsearch-docker
# FROM docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.3
FROM elasticsearch:5.6

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
