apiVersion: v1
kind: Service
metadata:
  name: phpadmin
  labels:
    name: phpadmin-service
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 80
  selector:
    app: phpadmin
  type: LoadBalancer
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: phpadmin-rc
spec:
  replicas: 1
  selector:
    app: phpadmin
  template:
    metadata:
      name: phpadmin
      labels:
        app: phpadmin
    spec:
      containers:
        - name: phpadmin
          image: phpmyadmin/phpmyadmin
          env:
           - name: PMA_HOST
             # Domain connenction NAME_SERVICE:PORT
             # IP server instaled mysql
             value: 192.168.109.132:3306
          ports:
           - containerPort: 80