apiVersion: v1
kind: ReplicationController
metadata:
  name: hello-world-rc
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - image: tutum/hello-world
          name: hello-word
          ports:
            - containerPort: 8080
              name: http